### ISSUE TITLE
NEON site with no name?

### ISSUE THREAD

**Issue by piersond** [lter/lterwg-som#14]
I've found a NEON site or sites with no "site_name" or "location_name."  Need to find a way to track this down to a keykey and data file.

**Comment by piersond** [comment]
Comes from these two google_IDs: 
"1F9Ll8HtpOlKEZpupS7rU2KXSKpWdzdzZ" 
"1lvmNTL7I1OQOl2QeS7gti5_aopiasyDL"

**Comment by srweintraub** [comment]
@piersond @srearl The issue is that the NEON 'raw' data files contain data from lots of sites. So, I can't manually write in site_code or location_name on the Location_data sheet of the key-key. Instead, the site code is a variable IN the data, named siteID. In the current key-key files, I put siteID = L1 in the Profile_data tab.

Seems like you need to add some code to deal with cases where multiple sites are in one data file, and maybe a key-key file mod. If you include 'site' as a unit level option for L1 , then you can write some code that does: if site_code & location_name are both blank and L1 unit level = site, use the L1 values for site_code/location_name.

**Comment by wwieder** [comment]
seems like this should be a pretty easy fix? I've moved the 'siteID' row in the Key-Key file from the location tab to the profile tab for NEON megapit, periodic and initial soil sampling file and re-homoged the data.  Is this all we need to do to address the issue?  If this looks good, would it be worth re-tarballing the database @srearl ?

**Comment by srweintraub** [comment]
@wwieder nice work! looks like that fixed it.

**Comment by wwieder** [comment]
I think we're OK now.  Still one NEON site without site or location provided, but I'm not sure how to find it...
