### ISSUE TITLE
Tarball errors, location & site code data

### ISSUE THREAD

**Issue by wwieder** [lter/lterwg-som#62]
`Location` data missing from BES, SSCZO and undetermined NEON site (and dataset).
`Site code` missing from New England Pastures and the same undetermined NEON site.
NE pastures also has no `network`

**Comment by srearl** [comment]
@wwieder Except for the NE pastures for which I need more details, these seem to be isolated cases and not any sort of systematic problem (see below). That said, part of the problem here may be that we were probably not consistent enough in our use of `location_name` and `site_name`. That could haunt us a bit. Note sure there is much we can do at this point but something to consider for a future version.

- BES: correct, `site_code` is BES but it does not have a `location_name`
- SSCZO: looks like *Moreland_Tian_SSCZO* is missing a location name but all other CZO dat have one
- NEON: this is that bizarre one related to issue #63 with 'initial char' being the only NEON data lacking, in this case, both a site and location name
- NE pasture: can you give me more detail about this one, I cannot find any data with *pasture* in the location or site name?

![Screenshot from 2019-09-19 10-51-57](https://user-images.githubusercontent.com/8332564/65268223-8d93ca00-dacb-11e9-91f7-a7eca301aefc.png)

**Comment by wwieder** [comment]
Location names were added.  These files have been rehomoged and are ready for the tarball
