### ISSUE TITLE
key-key consistency

### ISSUE THREAD

**Issue by wwieder** [lter/lterwg-som#63]
There seem to be several key-key files out there that are using slightly different variable names.  e.g. some of the neon data have `c_tot` and `soc` instead of `lyr_c_tot` and `lyr_soc`, [see example here.](https://docs.google.com/spreadsheets/d/1TLfzuh9k8nPvp-GkUNjoH6OyJ_AgnV0kM0UnZjw7gFA/edit#gid=0) 
Is this common in many datasets?  How can we check and throw an error when a dataset doesn't have the 'right' variable names that we're trying to align?

**Comment by srearl** [comment]
My thinking at this time is that this error is due to an incomplete update from key file version 1 to key file version 2. The history of the file suggests that the original key file (version 1) was manually enhanced with select version 2 features, and not updated with the key-file update script. This would cause a problem as some changes from key file v1 to v2, such as variable names, may not be updated. @wwieder does it seem plausible that it could have happened that way? If so, I think the solution in this case would be to revert the file to its original v1 state, update using the key file update script, add additional metadata as appropriate, then homog.

**Comment by wwieder** [comment]
Seems like this was only in `NEON_initialChar`.  Hopefully we're good to go.
